'use client';
import { useEffect, useRef, useState } from 'react';
import { Home, Search, Bell, ChevronDown, ChevronRight, Plus, MessageSquare, FileText, Layers, Compass, Sparkles, TrendingUp, SquareCheck, ChartNoAxesColumnIncreasing, Send, Square, Users, Paperclip, X, Check, LoaderCircle } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuRadioGroup, DropdownMenuRadioItem } from '@/components/ui/dropdown-menu';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import './kv-home.css';
import './topic-modules.css';
import SidebarHeaderTools from './sidebar-header-tools';
import SidebarRowActions from './sidebar-row-actions';

const modes=[{name:'智能问数',icon:MessageSquare,placeholder:'描述你要分析的问题，或把数据 / 报告交给趋势洞察…'},{name:'专题分析',icon:FileText,placeholder:'你想深入研究哪个主题？告诉我研究对象与目标…'},{name:'自由探索',icon:Compass,placeholder:'有什么值得探索的想法？从这里开始…'}];
const scenarios=[{name:'机会识别',icon:Search,prompt:'请分析未来 90 天轻户外消费市场的增长机会，识别值得布局的产品方向。'},{name:'供需诊断',icon:TrendingUp,prompt:'请分析轻户外消费者的未满足需求，以及现有产品供给的主要缺口。'},{name:'口径核查',icon:SquareCheck,prompt:'请核查这份研究中的数据定义、统计时间范围和指标口径，标记不一致之处。'},{name:'趋势追踪',icon:ChartNoAxesColumnIncreasing,prompt:'请追踪近 90 天轻户外消费趋势，区分持续增长信号与短期热点。'}];
const topicModules=[
{type:'核心产品',title:'产品 NSR 分析',desc:'深度挖掘社媒数据，分析特定产品的用户口碑和净推荐值趋势。',fields:['口碑分析','情感分布','购买驱动因素'],icon:ChartNoAxesColumnIncreasing},
{type:'竞争分析',title:'美妆竞品对比分析',desc:'对比两款美妆产品的优势、用户画像及市场定位，产出洞察报告。',fields:['多维度评测','目标人群差异','横向对比'],icon:TrendingUp},
{type:'监控与洞察',title:'产品词云看板',desc:'聚焦产品声量、词云与 NSR 指标，快速呈现用户反馈热点。',fields:['声量','词云','NSR'],icon:Layers},
{type:'产品提案',title:'食饮智能产品提案',desc:'输入品牌、品类与原料方向，系统自动补全趋势信息，创造产品提案。',fields:['概念生成','趋势提案','简报输出'],icon:Sparkles},
{type:'区域洞察',title:'区域洞察',desc:'选择研究省份与周期，生成覆盖宏观、人群与消费的区域洞察报告。',fields:['省份洞察','周期分析','图文报告'],icon:Compass},
{type:'竞品分析',title:'鞋服品牌竞品对比分析',desc:'聚焦鞋服品牌、品类与特征维度，生成品牌竞品对比报告。',fields:['品牌对比','价格带','特征分析'],icon:SquareCheck},
];
const tasks=[
{title:'轻户外消费者趋势专题',status:'running',statusLabel:'运行中',updated:'刚刚'},
{title:'星冰乐新品机会研究',status:'waiting',statusLabel:'等待回复',updated:'8 分钟前'},
{title:'竞品新品传播监测',status:'success',statusLabel:'成功',updated:'昨天'},
{title:'季度报告数据口径核查',status:'failed',statusLabel:'失败',updated:'2 天前'},
];
const conversations=[
{title:'帮我分析星冰乐 2025 年的产品卖点与口碑',updated:'刚刚'},
{title:'帮我做一份亚运舆情的日报',updated:'刚刚'},
{title:'NSR 的计算公式是什么',updated:'5 分钟前'},
{title:'星巴克今天有什么热点话题',updated:'2 小时前'},
{title:'鞋服的户外场景会有哪些',updated:'昨天'},
{title:'资生堂近期的社媒表现',updated:'星期一'},
{title:'美妆行业的消费趋势',updated:'8 月 28 日'},
];
const searchItems=[...tasks,...conversations];
function Mark(){return <svg viewBox="0 0 42 48" fill="none" aria-hidden="true"><path d="M21 3 37 12v9L21 12 7 20v-8L21 3ZM5 25l16 9 14-8v10l-14 9L5 36V25Z" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/><path d="m12 17 18 11M12 26l18 11" stroke="currentColor" strokeWidth="3"/></svg>}
function TaskStatus({status,label,updated}:{status:string;label:string;updated:string}){if(status==='success')return null;const description=`${label} · 更新于${updated}`;return <span className={`kv-task-status is-${status}`} title={description} aria-label={description}>{status==='running'?<LoaderCircle size={15}/>:<i aria-hidden="true"/>}</span>}
function fitTextarea(el:HTMLTextAreaElement|null){
if(!el)return;
el.style.height='auto';
const styles=getComputedStyle(el),lineHeight=parseFloat(styles.lineHeight)||22,padding=(parseFloat(styles.paddingTop)||0)+(parseFloat(styles.paddingBottom)||0),minHeight=parseFloat(styles.minHeight)||92,maxHeight=lineHeight*8+padding;
const contentHeight=el.scrollHeight;
el.style.height=`${Math.min(Math.max(contentHeight,minHeight),maxHeight)}px`;
el.style.overflowY=contentHeight>maxHeight?'auto':'hidden';
}
function TopicModules({selected,onSelect}:{selected:string;onSelect:(title:string)=>void}){return <section className="kv-topic-library"><div className="kv-topic-heading"><div><small>选择配置好的专题模块</small><h2>专题分析</h2></div><span>{topicModules.length} 个可用模块</span></div><div className="kv-topic-grid">{topicModules.map(module=>{const Icon=module.icon;return <article key={module.title} className={selected===module.title?'is-selected':''}><div className="kv-topic-type"><span><Icon size={15}/></span>{module.type}</div><h3>{module.title}</h3><p>{module.desc}</p><div className="kv-topic-fields">{module.fields.map(field=><span key={field}>{field}</span>)}</div><button onClick={()=>onSelect(module.title)}>{selected===module.title?'已选择':'立即使用'}<ChevronRight size={15}/></button></article>})}</div></section>}
export default function KVHome({onOpenSkills,onOpenQuestion,onOpenStarbucks}:{onOpenSkills:()=>void;onOpenQuestion:()=>void;onOpenStarbucks:()=>void}){
const onOpenReport=onOpenSkills;
const [mode,setMode]=useState('智能问数'),[scenario,setScenario]=useState(''),[value,setValue]=useState(''),[workspace,setWorkspace]=useState('研究空间'),[deliverable,setDeliverable]=useState('自动'),[files,setFiles]=useState<string[]>([]),[dialog,setDialog]=useState<'search'|'submit'|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[isGenerating,setIsGenerating]=useState(false),[tasksOpen,setTasksOpen]=useState(true),[conversationsOpen,setConversationsOpen]=useState(true),[renames,setRenames]=useState<Record<string,string>>({});
const inputRef=useRef<HTMLTextAreaElement>(null),fileRef=useRef<HTMLInputElement>(null);
useEffect(()=>fitTextarea(inputRef.current),[value,mode]);
function fill(text:string){setValue(text);setError('');requestAnimationFrame(()=>inputRef.current?.focus())}
function reset(){setMode('智能问数');setScenario('');setValue('');setFiles([]);setError('');setDeliverable('自动');setWorkspace('研究空间');setIsGenerating(false);inputRef.current?.focus()}
function submit(){if(isGenerating){setIsGenerating(false);return}if(!value.trim()){setError('请先写下你想分析的问题。');inputRef.current?.focus();return}setError('');if(mode==='智能问数'||mode==='自由探索'){onOpenStarbucks();return}setIsGenerating(true);setDialog('submit')}
return <SidebarProvider className={`kv-app${mode==='专题分析'?' mode-topic':''}`} style={{'--sidebar-width':'260px'} as React.CSSProperties}>
<Sidebar className="kv-sidebar" collapsible="icon"><SidebarHeader className="kv-side-header"><div className="sidebar-head-row"><div className="kv-brand"><Mark/><strong>Social Research Pro</strong></div><SidebarHeaderTools items={searchItems.map(item=>item.title)} onSelect={item=>{setMode('智能问数');fill(`请继续讨论：${item}。`)}}/></div><button className="kv-new" onClick={reset} aria-label="新建分析" title="新建分析"><Plus size={24}/>新建分析</button></SidebarHeader>
<SidebarContent className="kv-side-content"><nav aria-label="主导航">{modes.slice(0,2).map(m=><button key={m.name} className="kv-nav" aria-current={mode===m.name?'page':undefined} onClick={()=>setMode(m.name)}><m.icon size={22}/>{m.name}</button>)}<button className="kv-nav" onClick={onOpenReport}><Layers size={22}/>资产中心</button><button className="kv-nav" aria-current={mode==='自由探索'?'page':undefined} onClick={()=>setMode('自由探索')}><Compass size={22}/>自由探索</button></nav><div className="kv-history"><section className="kv-sidebar-section"><button className="kv-section-heading" aria-expanded={tasksOpen} onClick={()=>setTasksOpen(v=>!v)}><span>任务</span><ChevronRight size={13}/></button>{tasksOpen&&<div className="kv-section-items">{tasks.map(task=><button className="kv-task-row" key={task.title} onClick={()=>{setMode('专题分析');fill(`请继续处理任务：${task.title}。`)}}><span className="kv-task-title">{task.title}</span><span className="kv-task-tail"><TaskStatus status={task.status} label={task.statusLabel} updated={task.updated}/><time>{task.updated}</time></span></button>)}</div>}</section><section className="kv-sidebar-section kv-conversations"><button className="kv-section-heading" aria-expanded={conversationsOpen} onClick={()=>setConversationsOpen(v=>!v)}><span>最近对话</span><ChevronRight size={13}/></button>{conversationsOpen&&<div className="kv-section-items">{conversations.map(item=><div className="kv-conversation-row sidebar-action-row" key={item.title}><button className="sidebar-row-primary" onClick={()=>{if(item.title.includes('星冰乐 2025'))onOpenStarbucks();else if(item.title.includes('亚运舆情'))onOpenQuestion();else{setMode('智能问数');fill(`请继续讨论：${item.title}。`)}}}><span>{renames[item.title]||item.title}</span><time>{item.updated}</time></button><SidebarRowActions title={renames[item.title]||item.title} onRename={next=>setRenames({...renames,[item.title]:next})}/></div>)}</div>}</section></div></SidebarContent>
<SidebarFooter className="kv-side-footer"><span className="kv-team-icon"><Users size={22}/></span><span>品牌研究团队</span><DropdownMenu><DropdownMenuTrigger aria-label="团队信息"><ChevronRight size={19}/></DropdownMenuTrigger><DropdownMenuContent className="kv-menu" side="top"><DropdownMenuItem disabled>品牌研究团队 · 演示工作空间</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar>
<main className="kv-main"><header className="kv-header"><div><SidebarTrigger className="kv-sidebar-trigger"/><Home size={22}/><span>研究空间</span><i>/</i><b>新建分析</b></div><div className="kv-header-actions"><button aria-label="搜索最近任务" onClick={()=>{setQuery('');setDialog('search')}}><Search size={23}/></button><DropdownMenu><DropdownMenuTrigger aria-label="通知"><Bell size={22}/></DropdownMenuTrigger><DropdownMenuContent className="kv-menu" align="end"><DropdownMenuItem disabled>暂无新通知</DropdownMenuItem></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger aria-label="账户菜单" className="kv-account"><span>S</span><ChevronDown size={17}/></DropdownMenuTrigger><DropdownMenuContent className="kv-menu" align="end"><DropdownMenuItem disabled>SRP 演示账户</DropdownMenuItem><DropdownMenuItem onClick={reset}>开始新的分析</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
<section className="kv-start"><div className="kv-welcome"><h1><span>趋势洞察</span>，智能分析伙伴</h1></div>
<Tabs value={mode} onValueChange={v=>setMode(String(v))} className="kv-tabs"><TabsList variant="default" aria-label="分析模式">{modes.map((m,i)=><TabsTrigger key={m.name} value={m.name}>{i===0?<Sparkles size={22}/>:<m.icon size={22}/>}<span>{m.name}</span></TabsTrigger>)}</TabsList>
{modes.map(m=><TabsContent key={m.name} value={m.name} className="kv-panel">{m.name==='专题分析'&&<TopicModules selected={scenario} onSelect={setScenario}/>}<div className="kv-capabilities" aria-label="场景能力"><span className="kv-capability-label">场景能力</span>{scenarios.map(s=><button key={s.name} aria-pressed={scenario===s.name} onClick={()=>{setScenario(s.name);fill(s.prompt)}}><s.icon size={21}/>{s.name}</button>)}</div>
<div className="kv-composer-anchor"><form className="kv-composer" onSubmit={e=>{e.preventDefault();submit()}}><textarea ref={mode===m.name?inputRef:undefined} value={value} onChange={e=>{setValue(e.target.value);setError('')}} placeholder={m.placeholder} aria-label={`${m.name}分析问题`} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}}/>{files.length>0&&<div className="kv-attachments">{files.map(f=><span key={f}><Paperclip size={14}/>{f}<button type="button" aria-label={`移除 ${f}`} onClick={()=>setFiles(files.filter(x=>x!==f))}><X size={13}/></button></span>)}<small>仅展示文件名，不上传或解析</small></div>}
<div className="kv-tools"><div className="kv-tool-group"><button type="button" className="kv-attach" onClick={()=>fileRef.current?.click()}><span><Plus size={23}/></span><span>添加附件</span></button><DropdownMenu><DropdownMenuTrigger type="button"><FileText size={20}/>模板</DropdownMenuTrigger><DropdownMenuContent className="kv-menu" side="top">{scenarios.map(s=><DropdownMenuItem key={s.name} onClick={()=>{setScenario(s.name);fill(s.prompt)}}><s.icon size={16}/>{s.name}模板</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger type="button"><Layers size={21}/>{workspace}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="kv-menu" side="top"><DropdownMenuRadioGroup value={workspace} onValueChange={setWorkspace}>{['研究空间','品牌策略','消费者洞察'].map(w=><DropdownMenuRadioItem key={w} value={w}>{w}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger type="button"><FileText size={21}/>交付物：{deliverable}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="kv-menu" side="top"><DropdownMenuRadioGroup value={deliverable} onValueChange={setDeliverable}>{['自动','研究报告','数据摘要'].map(d=><DropdownMenuRadioItem key={d} value={d}>{d}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div><button type="submit" className={`kv-send${isGenerating?' is-stopping':''}`} aria-label={isGenerating?'停止生成':'发送'} title={isGenerating?'停止生成':'发送'}>{isGenerating?<Square size={15} fill="currentColor"/>:<Send size={18}/>}</button></div></form></div></TabsContent>)}</Tabs>
<input hidden type="file" multiple ref={fileRef} onChange={e=>{setFiles([...new Set([...files,...Array.from(e.target.files||[]).map(f=>f.name)])]);e.target.value=''}}/>{error&&<p className="kv-error" role="alert">{error}</p>}<p className="kv-footnote">内容由 AI 生成，请核实重要信息。<span>交互演示</span></p></section></main>
<Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className="kv-dialog"><DialogTitle>{dialog==='search'?'搜索任务与对话':'分析需求已整理'}</DialogTitle><DialogDescription>{dialog==='search'?'选择一项记录，将内容带回输入框。':'这是前端原型，发送用于预览需求，不会执行真实检索。'}</DialogDescription>{dialog==='search'?<><input className="kv-search-input" aria-label="搜索任务与对话" placeholder="输入名称…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="kv-search-results">{searchItems.filter(item=>item.title.includes(query)).map(item=><button key={item.title} onClick={()=>{fill(`请继续研究：${item.title}。`);setDialog(null)}}><MessageSquare size={17}/>{item.title}</button>)}{!searchItems.some(item=>item.title.includes(query))&&<p>没有匹配的记录</p>}</div></>:<><div className="kv-brief"><p>{value}</p><dl><div><dt>分析模式</dt><dd>{mode}</dd></div><div><dt>研究空间</dt><dd>{workspace}</dd></div><div><dt>交付物</dt><dd>{deliverable}</dd></div>{scenario&&<div><dt>场景能力</dt><dd>{scenario}</dd></div>}{files.length>0&&<div><dt>演示附件</dt><dd>{files.length} 个（未上传）</dd></div>}</dl></div><button className="kv-dialog-done" onClick={()=>setDialog(null)}><Check size={17}/>返回继续编辑</button></>}</DialogContent></Dialog>
</SidebarProvider>}
