'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUp, ArrowUpRight, ArrowLeft, Plus, Sparkles, FileText, MessageSquare, FolderOpen, ChevronRight, Check, Download, X, Leaf, Globe, Paperclip, Search, TrendingUp, PanelRight, Compass, CheckCheck } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Progress } from '@/components/ui/progress';
import { flushSync } from 'react-dom';
import KVHome from './kv-home';
import QuestionTaskPage from './qa-task';
import SkillMarket from './skill-market';
const question='未来 90 天，轻户外穿搭有哪些上升趋势？哪些产品最有机会成为爆款？';
const suggestions=['未来 90 天，轻户外穿搭有哪些上升趋势？','哪些轻户外单品值得品牌优先布局？','轻户外消费者正在讨论什么新需求？'];
const signals=[{title:'通勤轻户外',en:'EVERYDAY OUTDOOR',growth:'+128%',color:'#51882d',text:'从周末目的地，走进工作日。消费者更关注一衣多穿与低调的功能感。',tags:['通勤可穿','轻量收纳','无场景切换']},{title:'轻量防护',en:'LIGHT PROTECTION',growth:'+86%',color:'#4679b8',text:'防晒只是起点。透气、不闷汗与真实体感，成为更有说服力的选择理由。',tags:['透气体感','轻薄防风','便携防护']},{title:'城市到山野',en:'CITY TO TRAIL',growth:'+64%',color:'#c07b40',text:'短途徒步与城市漫游共享一套衣橱，日常审美正在改写专业装备的表达。',tags:['周末短途','自然色系','轻徒步']}];
function Brand({small=false}:{small?:boolean}){return <div className={small?'brand-mark small':'brand-mark'}><Sparkles size={small?16:22}/></div>}
function TrendChart(){return <svg className="trend-chart" viewBox="0 0 650 240" role="img" aria-label="模拟指数：通勤轻户外100到228，轻量防护100到186，城市到山野100到164"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a7d77d" stopOpacity=".32"/><stop offset="100%" stopColor="#a7d77d" stopOpacity="0"/></linearGradient></defs>{[45,90,135,180].map((y,i)=><g key={y}><line x1="42" x2="620" y1={y} y2={y} stroke="#e9ece9" strokeDasharray="4 5"/><text x="7" y={y+5} fill="#7a837d" fontSize="12">{250-i*50}</text></g>)}<path d="M45 180 L110 170 L175 157 L240 162 L305 127 L370 113 L435 100 L500 85 L560 73 L620 65 L620 198 L45 198Z" fill="url(#fill)"/><polyline points="45,180 110,170 175,157 240,162 305,127 370,113 435,100 500,85 560,73 620,65" stroke="#659c3d" strokeWidth="3" fill="none"/><polyline points="45,180 110,182 175,169 240,156 305,158 370,144 435,130 500,121 560,108 620,103" stroke="#6b92c7" strokeWidth="2.5" fill="none"/><polyline points="45,180 110,178 175,181 240,175 305,160 370,158 435,150 500,143 560,136 620,122" stroke="#d19a68" strokeWidth="2.5" fill="none"/>{['6 月 12 日','7 月 01 日','7 月 20 日','8 月 08 日','8 月 27 日','9 月 09 日'].map((t,i)=><text key={t} x={43+i*109} y="227" fill="#7a837d" fontSize="12">{t}</text>)}</svg>}
export default function Home(){
const[view,setView]=useState<'chat'|'report'|'qa'|'starbucks'|'skills'>('chat'),[stage,setStage]=useState<'empty'|'brief'|'running'|'done'>('empty'),[input,setInput]=useState(''),[submitted,setSubmitted]=useState(question),[scope,setScope]=useState('中国大陆 · 小红书 / 抖音 · 近 90 天'),[progress,setProgress]=useState(0),[panel,setPanel]=useState(false),[follow,setFollow]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[file,setFile]=useState('');
const fileRef=useRef<HTMLInputElement>(null),chatRef=useRef<HTMLDivElement>(null);
useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool={name:'open_srp_demo_view',title:'打开 SRP 演示页面',description:'切换到研究对话或预设的模拟趋势报告，不执行真实研究。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['chat','report']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const v=(input as {view?:unknown})?.view;if(v!=='chat'&&v!=='report')throw new Error('view must be chat or report');flushSync(()=>setView(v));return {view:v,demo:true}}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
},[]);
useEffect(()=>{if(stage!=='running')return;const t=setInterval(()=>setProgress(p=>Math.min(100,p+20)),650);return()=>clearInterval(t)},[stage]);
useEffect(()=>{if(progress===100&&stage==='running')setStage('done')},[progress,stage]);
useEffect(()=>{chatRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[stage]);
function reset(){setStage('empty');setView('chat');setInput('');setError('');setFile('');setProgress(0);setAnswer('')}
function send(text=input){if(!text.trim()){setError('写下一个想研究的问题，就可以开始。');return}setSubmitted(text.trim());setStage('brief');setInput('');setError('')}
function ask(text=follow){if(!text.trim())return;setFollow('');setAnswer(text.includes('限制')?'这份演示报告没有真实数据采集。24,680 篇内容、趋势指数与消费者语句均为虚构。正式研究需要：可追溯原文、去重与抽样方法、跨平台口径校准，以及与销量等独立信号的交叉验证。讨论增长不能直接推断销售增长。':text.includes('计划')?'两周验证计划：第 1–3 天，确定通勤轻量外套的样衣与目标人群；第 4–7 天，分别制作“全天舒适”和“一衣多场景”两组内容；第 8–11 天，以同等预算小范围测试；第 12–14 天，对比有效询单、转化及体验反馈，再决定是否扩大投入。以上为演示建议，需结合实际预算与产品能力调整。':`关于“${text.trim()}”：建议优先验证「通勤可穿的轻量防风外套」。模拟样本里，通勤轻户外讨论增长 128%，但这不等同于销量预测。先用“全天舒适”与“一衣多场景”两组内容测试，结合有效询单、转化和退货原因判断是否扩大投入。`)}
if(view==='chat')return <KVHome onOpenSkills={()=>setView('skills')} onOpenQuestion={()=>setView('qa')} onOpenStarbucks={()=>setView('starbucks')}/>;
if(view==='qa'||view==='starbucks')return <QuestionTaskPage onBack={()=>setView('chat')} caseType={view==='qa'?'asian':'frappuccino'} onSelectCase={next=>setView(next==='asian'?'qa':'starbucks')}/>;
if(view==='skills')return <SkillMarket onBack={()=>setView('chat')} onOpenChat={()=>setView('chat')}/>;
return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader className="side-head"><div className="wordmark"><Brand/><div>SRP <span>趋势洞察</span></div></div><button className="new-button" onClick={reset}><Plus size={17}/>新建研究</button></SidebarHeader><SidebarContent className="side-content"><nav><button className="nav-item" onClick={()=>setView('chat')}><MessageSquare size={17}/>研究对话</button><button className={view==='report'?'nav-item selected':'nav-item'} onClick={()=>setView('report')}><FileText size={17}/>洞察报告<span className="nav-count">1</span></button></nav><div className="side-label">最近研究</div><button className="project-item" onClick={()=>{setView('chat');if(stage==='empty'){setSubmitted(question);setStage('done')}}}><span className="project-dot"/>轻户外穿搭趋势研究<span className="project-sub">今天 · 3 个趋势信号</span></button><div className="sidebar-note"><Compass size={19}/><b>从问题，走向下一步。</b><p>把市场信号转化为<br/>有依据的品牌决策。</p></div></SidebarContent><SidebarFooter className="side-footer"><div className="avatar">林</div><div>林知远<small>品牌策略团队</small></div><span className="workspace-tag">演示空间</span></SidebarFooter></Sidebar>
<main className={`app-main ${view==='report'?'report-main':''}`}><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>品牌研究空间</span><ChevronRight size={14}/><b>{view==='report'?'轻户外穿搭趋势研究':'研究对话'}</b></div><div className="header-meta"><i/>演示模式<span/>仅示例内容</div></header>
<div className="report-shell"><div className="report-toolbar"><button onClick={()=>setView('chat')}><ArrowLeft size={16}/>返回对话</button><div><span className="saved"><Check size={14}/>演示报告</span><button onClick={()=>window.print()}><Download size={15}/>导出 PDF</button><button onClick={()=>setPanel(!panel)}><PanelRight size={16}/>追问报告</button></div></div><div className={`report-layout ${panel?'with-panel':''}`}><article className="report-paper"><div className="report-cover"><div className="cover-copy"><span className="cover-eyebrow">SRP INSIGHTS / 2026.09</span><span className="report-type">消费趋势观察</span><h1>从城市，<br/>走向山野。</h1><p>轻户外穿搭趋势<br/>与未来 90 天产品机会</p><div className="cover-meta">中国大陆 · 小红书 / 抖音<br/>观察周期 2026.06.12 — 09.09</div></div><div className="cover-image"><img src="outdoor.png" alt="两位穿白色与鲜绿色轻量外套的成人在山野徒步，AI 场景示意"/><span>LIGHT OUTDOOR · EVERYDAY LIFE</span></div></div><div className="report-body"><div className="demo-banner"><span>演示数据</span>数字、样本与结论均为虚构，展示研究报告的呈现方式。</div><nav className="report-toc"><a href="#summary">01 核心发现</a><a href="#signals">02 趋势信号</a><a href="#evidence">03 消费者声音</a><a href="#opportunity">04 产品机会</a></nav>
<section id="summary"><div className="section-index">01 / THE BIG PICTURE</div><h2>消费者要的，是「每天都能穿的户外」。</h2><p className="lead">功能走向日常，审美变得轻盈。演示样本显示，轻户外的关注点正从“我能去多远”，转向“它能陪我多久”。品牌值得验证的机会，是把轻量防护放进真实的生活动线。</p><div className="metrics"><div><span>样本内容量</span><strong>24,680<small>篇</small></strong><p>两平台模拟观察样本</p></div><div><span>通勤轻户外讨论增幅</span><strong className="green">+128<small>%</small></strong><p>期末指数相对期初</p></div><div><span>上升趋势信号</span><strong>3<small>个</small></strong><p>待真实数据进一步验证</p></div></div></section>
<section id="signals"><div className="section-index">02 / EMERGING SIGNALS</div><div className="section-title"><h2>三个信号，一次生活方式的迁移。</h2><span className="tiny-label">模拟趋势指数 · 期初 = 100</span></div><div className="chart-block"><div className="chart-title"><b>通勤轻户外，呈现更强的持续增长。</b><div className="legend">{signals.map(s=><span key={s.title}><i style={{background:s.color}}/>{s.title}</span>)}</div></div><TrendChart/><p className="chart-note">指数用于对比相对变化，不代表真实市场规模或销量。</p></div><div className="signal-grid">{signals.map((s,i)=><div className="signal-card" key={s.title}><div className="signal-top"><span>0{i+1}</span><strong style={{color:s.color}}>{s.growth}<ArrowUpRight size={19}/></strong></div><small>{s.en}</small><h3>{s.title}</h3><p>{s.text}</p><div className="tag-list">{s.tags.map(t=><span key={t}>{t}</span>)}</div></div>)}</div></section>
<section id="evidence"><div className="section-index">03 / HUMAN CONTEXT</div><h2>让需求具体的，是生活里的小瞬间。</h2><div className="evidence-layout"><div className="evidence-photo"><img src="outdoor.png" alt="轻户外生活场景，AI 生成示意"/><span>场景示意 · AI 生成</span></div><div className="quotes"><div><span className="source-chip">示例内容 A · 小红书场景</span><blockquote>“早上穿去上班，周末直接去徒步。不想为了不同场合再买一件。”</blockquote><p>需求解读：多场景适配，比堆叠功能更容易被理解。</p></div><div><span className="source-chip blue">示例内容 B · 抖音场景</span><blockquote>“真正打动我的不是参数，是走完一段路，背后没有闷汗。”</blockquote><p>需求解读：用可感知的体感，解释轻量防护。</p></div><details><summary>查看 6 条示例证据与口径<ChevronRight size={14}/></summary><ul>{['A · 通勤与徒步，希望一衣多场景。','B · 走路不闷汗，比参数更重要。','C · 地铁与室外温差，需要轻薄外搭。','D · 不想穿得太专业，希望日常也好搭。','E · 周末只带小包，衣服能收纳更好。','F · 喜欢自然色，希望有一处亮色。'].map(t=><li key={t}>{t}</li>)}</ul><p>全部为撰写的示例语句，不对应真实账号或帖子。正式研究需补充原文、采集时间与抽样方法。</p></details></div></div></section>
<section id="opportunity"><div className="section-index">04 / WHAT TO DO NEXT</div><h2>优先验证一个产品，再决定下一步。</h2><div className="opportunity-grid"><div className="matrix"><div className="matrix-label">机会潜力 ↑</div><div className="quadrants"><span className="quadrant-label">优先验证</span><span className="matrix-dot dot-a">通勤防风外套</span><span className="matrix-dot dot-b">轻量防晒衣</span><span className="matrix-dot dot-c">专业硬壳</span><span className="matrix-dot dot-d">基础速干 T 恤</span></div><div className="matrix-label bottom">竞争强度 →</div><small>策略判断示意，非量化评分</small></div><div className="recommendations">{[['产品：轻量外套先行','验证低噪面料、透气体感与便携收纳，保留适合通勤的简洁轮廓。'],['内容：展示完整的一天','以“地铁 → 办公室 → 公园”讲清多场景价值，用穿着过程解释功能。'],['节奏：小批量、两组内容','先测试体感与场景两种表达，结合询单、转化和退货原因再扩大投入。']].map(([t,p],i)=><div key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</div></div><div className="takeaway"><Leaf size={25}/><div><b>把户外的功能，做成日常的理由。</b><p>下一步：将趋势假设转化为产品与内容验证。</p></div><button onClick={()=>{setPanel(true);ask('帮我生成一个两周验证计划')}}>展开行动计划<ArrowUpRight size={16}/></button></div></section><footer className="report-end"><div className="wordmark"><Brand small/><b>SRP</b><span>让洞察，走向行动。</span></div><p>研究口径：全部数据为预设模拟样本；图像为 AI 生成。未进行真实采集、去重、统计显著性检验或销售预测。正式交付需补齐来源、方法与限制。</p><span>END OF REPORT / 2026</span></footer></div></article>
{panel&&<aside className="ask-panel"><header><span><Sparkles size={16}/>继续探索</span><button aria-label="关闭追问" onClick={()=>setPanel(false)}><X size={17}/></button></header><div className="ask-content"><span className="context-chip"><FileText size={14}/>基于当前报告</span><h3>把一个发现，<br/>变成下一步行动。</h3><p>追问趋势原因，或把结论转成产品与内容计划。</p>{['哪个趋势值得优先投入？','帮我生成一个两周验证计划','这份报告有哪些证据限制？'].map(t=><button className="follow-suggestion" key={t} onClick={()=>ask(t)}>{t}<ArrowUpRight size={14}/></button>)}{answer&&<div className="follow-answer" aria-live="polite"><Brand small/><p>{answer}</p><small>演示回复 · 未调用真实 AI</small></div>}</div><form onSubmit={e=>{e.preventDefault();ask()}}><textarea aria-label="追问报告" value={follow} onChange={e=>setFollow(e.target.value)} placeholder="围绕这份报告继续提问…"/><button className="send" aria-label="发送追问"><ArrowUp size={17}/></button></form></aside>}</div></div></main></SidebarProvider>}
